---
- hosts: mywebserver
  become: yes
  tasks:
    - name: install webserver on ec2-linux
      yum:
        name: "{{myjavapackageredhat}}"
        state: present

    - name: check status of webserver on ec2-linux
      service:
        name: "{{mywebpack}}"
        state: stopped
      when: ansible_os_family == "RedHat"

